export interface IconCategory {
  id: string;
  label: string;
  icons: string[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    id: "most-popular",
    label: "Most Popular",
    icons: [
      "home",
      "dumbbell",
      "user",
      "plane",
      "person-standing",
      "globe",
      "moon",
      "leaf",
      "message-circle",
      "eye",
      "sparkles",
      "star",
      "coffee",
      "droplet",
      "flame",
      "zap",
      "music",
      "camera",
      "image",
      "mail",
      "phone",
      "message-square",
    ],
  },
  {
    id: "health-sports",
    label: "Health & Sports",
    icons: [
      "dumbbell",
      "bike",
      "heart",
      "activity",
      "apple",
      "person-standing",
      "utensils",
      "footprints",
      "bed",
      "wind",
      "droplets",
      "pill",
    ],
  },
  {
    id: "education",
    label: "Education",
    icons: [
      "book-open",
      "graduation-cap",
      "pencil",
      "lightbulb",
      "brain",
      "microscope",
      "calculator",
      "palette",
      "language",
      "trophy",
    ],
  },
  {
    id: "work",
    label: "Work",
    icons: [
      "briefcase",
      "laptop",
      "target",
      "trending-up",
      "calendar",
      "clock",
      "folder",
      "file-text",
      "clipboard",
      "check-square",
    ],
  },
  {
    id: "entertainment",
    label: "Entertainment",
    icons: [
      "music",
      "headphones",
      "tv",
      "film",
      "gamepad-2",
      "book",
      "palette",
      "camera",
      "popcorn",
      "party-popper",
    ],
  },
  {
    id: "travel",
    label: "Travel",
    icons: [
      "plane",
      "car",
      "train",
      "ship",
      "map",
      "compass",
      "luggage",
      "mountain",
      "palm-tree",
      "tent",
    ],
  },
  {
    id: "shopping",
    label: "Shopping",
    icons: [
      "shopping-bag",
      "shopping-cart",
      "tag",
      "credit-card",
      "wallet",
      "gift",
      "package",
      "store",
    ],
  },
  {
    id: "nature",
    label: "Nature",
    icons: [
      "leaf",
      "tree-deciduous",
      "flower-2",
      "sun",
      "moon",
      "cloud",
      "cloud-rain",
      "snowflake",
      "droplet",
      "flame",
    ],
  },
];
